### ISSUE TITLE
MAIN SITE - BUG - Interview main page

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#742] opened 2019-10-01 21:53 UTC
Just noticed while adding a new interview ON DEV that the enlargement of the picture of the person interviewed doesnit use are regular script anymore. It does still seem to work on the PROD version.

**Comment by nguillaumin** [comment] 2020-08-10 17:32
I cannot reproduce this, so closing it.

**Comment by stgraveyard** [comment] 2020-08-10 17:38
Nico, 

Now it also doesn't work on prod anymore. It is no big deal, but it's all in the details, right? ;-) Here is what I mean. 

When going to the main review page and you click on a screenshot, enlargement looks like this : 

![image](https://user-images.githubusercontent.com/4339294/89812733-dff53380-db40-11ea-9eaa-af80b0f33e8d.png)

Keeping the main page in the BG, because we have a script for this. 

Now when doing this on the main interview page : 

![image](https://user-images.githubusercontent.com/4339294/89812789-f602f400-db40-11ea-9bbb-b73221a8d101.png)

(it acts like a link to a photo overthere). 

That was what I meant.

**Comment by nguillaumin** [comment] 2020-08-10 20:20
Ok, I misunderstood, I'll have a look.

**Comment by nguillaumin** [comment] 2020-08-11 20:09
I could not find trace of that in the Git history so I wonder if that ever worked :wink: but it was easy enough to add. Fixed on dev.

**Closed by nguillaumin** 2020-08-11 20:09 UTC
Labels: scope:main-site, type:bug

**Comment by stgraveyard** [comment] 2020-08-11 21:05
Are you sure, doesn't work for me on dev.stonish.net?

**Comment by nguillaumin** [comment] 2020-08-12 06:22
Duh, I forgot to push my changes! Will do tonight.

**Comment by stgraveyard** [comment] 2020-08-12 07:52
I currently have no AL offline, so if it is ok with you I like to test on dev for awhile until I jump on the code bandwagon...

**Comment by nguillaumin** [comment] 2020-08-12 16:55
It does work on the dev server for me actually, I did push my changes yesterday. But I think we're still not talking about the same thing :wink: I added the lightbox here: 

![lb1](https://user-images.githubusercontent.com/762512/90044036-558e0a80-dccd-11ea-9b58-a5a2d073248a.png)

But you want it here:

![lb2](https://user-images.githubusercontent.com/762512/90044048-5b83eb80-dccd-11ea-8663-aaef70aaf518.png)

So I'll make another change.

**Comment by nguillaumin** [comment] 2020-08-12 17:13
Ok this should be fixed for good now, working on dev!
