### ISSUE TITLE
New release with new developer

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/atari-legend#135] opened 2021-04-23 14:29 UTC
Hello all,

I have a question. I have an upcoming interview with Jonathan Thomas, the creator of the new enhanced STe version of Lotus. When I go to the main page of Lotus, I see this : 

![image](https://user-images.githubusercontent.com/4339294/115886015-cedf1f00-a450-11eb-9ee0-b9c555194a19.png)

So there is a new release for 2021. What I don't understand is where I can link Jonathan now, as he is the developer of this specific new release. I don't want to make a new game entry (like we have done with eg. Turrican 2 - This does not make sense to me at all! please opinions), but adding Jonathan to the main page as a developer, is that correct? Maybe we should be able to add some kind of note? 

What do you think?

Cheers,
Maarten

**Comment by nguillaumin** [comment] 2021-04-23 20:38
Yes, I did create this release actually, and I had the same question :smile: Currently in the database we do not support specific individuals on releases, we can only associate crews to a release. Unfortunately I don't think Jonathan and the other people who work on this are part of a crew?

So for now, not much we can do. There is a "note" field on the release but currently it is not shown on the main site as it was intended for internal notes...

![1](https://user-images.githubusercontent.com/762512/115927256-71fd5c00-a484-11eb-8022-5802171412ac.png)

I think the right solution would be to allow associating individual with releases, but it's a fair amount of work to support this.

**Comment by MugUK** [comment] 2021-04-23 21:02
JunoSix did the audio engine tweaks. Who else helped?

**Comment by stgraveyard** [comment] 2021-04-23 21:29
Jamie and Jonathan. 

@nguillaumin I don't know if we should add the developers to a release. Maybe the correct solution is adding the devs to the main game entry and specify a bit with a comment on that level, or link a release to the developer between brackets or something. 
I do understand only a publisher is linked to a release, but we did not think of these homebrews. Maybe in this case a new game entry IS the correct solution? I don't know...

**Comment by nguillaumin** [comment] 2021-04-24 08:56
They mention [other people on their GitHub](https://github.com/jonathanopalise/lotus-ste#credits), that's why I had "crew" in mind, if they were part of named crew we could have added it to this release.

I think it's a bit of a special case, it's not that common that individuals will "patch" an existing game to improve it. So I would say we shouldn't change our database structure for such uncommon cases. Simplest for me would be to keep it as a separate release and use the Note field to describe who is involved, and publish this Note field on the main site.

**Comment by stgraveyard** [comment] 2021-04-24 20:45
Yes, problem is they will not come up in the search field, interviews (which is coming soon) is not linked to the person, the game itself is not linked to the person. It is not a good solution. I also think there are more cases like this eg. DROID which got an STe version last year...

**Comment by stgraveyard** [comment] 2021-04-24 20:58
This is the new  version of droid : https://www.atarilegend.com/games/6451

Our database really isn't consistant like this ...

**Comment by nguillaumin** [comment] 2021-04-25 08:42
The "correct" solution for me in terms of DB structure would be to make it a release but associate extra developers with it (which is not possible currently), especially since they patched the original game. This is just a different version of the game. If we could associate individuals with releases then we could have the search, interviews, etc working.

In the meantime since we cannot associate individuals to releases, if you prefer to create a new game entry for it it's fine by me.

**Comment by stgraveyard** [comment] 2021-04-25 10:05
Hi Nico, I agree with, I think.
The reason I am being a bit pushy is that I notice more and more people are getting enthousiastic about Atari Legend. Since the Lotus video on friday I have gotten a few pms from developers who are interested in interviews. Same for Jonathan Thomas. He also stressed out that if the scene would show some more support for co developer Jamie's work (who also did the enhanced version of Droid), they would be more motivated. So I am now in contact with Jamie who really wants to be part of a new video and interview.
And last night, I was in touch with a former STe developer, who is now making a game for the new Atari VCS. I sent him the link to the lotus video, and he got really excited. I am planning a new video of this guys work and ince this video is done he wants to share it using the official Atari channels.

So anyway, all small patatoes but when we post interviews, we really should be able to link it to their games, make it look as professional as possible. We are really building something cool, all together.  

So I guess for now I will have to make a new game release so the upcominh interview will be linked.

**Comment by nguillaumin** [comment] 2021-05-08 17:01
Closing for now assuming there's nothing to do in the code. Creation of a new game is possible if desired.

**Closed by nguillaumin** 2021-05-08 17:01 UTC
Labels: scope:main-site, type:question
